# .github/workflows/python-tests.yml
name: Python Tests

on:
  pull_request

jobs:
  test:
    name: PyTest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10.6
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: python -m pytest
